# Copyright 2025 The TransferQueue Team
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
import itertools
import logging
import os
from typing import Any

import torch
from tensordict import NonTensorStack, TensorDict
from torch import Tensor

from transfer_queue.metadata import BatchMeta
from transfer_queue.storage.clients.factory import StorageClientFactory
from transfer_queue.storage.managers.base import TransferQueueStorageManager
from transfer_queue.storage.managers.factory import TransferQueueStorageManagerFactory

logger = logging.getLogger(__name__)
logger.setLevel(os.getenv("TQ_LOGGING_LEVEL", logging.WARNING))


@TransferQueueStorageManagerFactory.register("KV")
class KVStorageManager(TransferQueueStorageManager):
    """
    A storage manager that uses a key-value (KV) backend (e.g., YuanRong) to store and retrieve tensor data.
    It maps structured metadata (BatchMeta) to flat lists of keys and values for efficient KV operations.
    """

    def __init__(self, config: dict[str, Any]):
        """
        Initialize the KVStorageManager with configuration.
        """
        client_name = config.get("client_name", None)
        if client_name is None:
            raise ValueError("Missing client_name in config")
        super().__init__(config)
        self.storage_client = StorageClientFactory.create(client_name, config)

    @staticmethod
    def _generate_keys(field_names: list[str], global_indexes: list[int]) -> list[str]:
        """
        Generate KV keys in the format 'global_index@field_name' for all sample-field pairs.
        Keys are generated in sorted order by field name first, then by global index,
        ensuring consistent ordering for batched operations.

        Args:
            field_names : list of field names.
            global_indexes : list of global indexes.
        Returns:
            list[str]: List of keys, e.g., ['0@field_a', '1@field_a', '0@field_b', ...]
        """
        return [f"{index}@{field}" for field, index in itertools.product(sorted(field_names), global_indexes)]

    @staticmethod
    def _generate_values(data: TensorDict) -> list[Tensor]:
        """
        Extract and flatten tensor values from a TensorDict in field-major order.
        Values are ordered by sorted field names, then by row (sample) order within each field.
        This matches the key order generated by `_generate_keys`.

        Args:
            data (TensorDict): Input data where keys are field names and values are tensors.
        Returns:
            list[Tensor]: Flattened list of tensors, e.g.,
                          [data[field_a][0], data[field_a][1], data[field_a][2], ..., data[field_b][0], ...]
        """
        return [row_data for field in sorted(data.keys()) for row_data in data[field]]

    @staticmethod
    def _merge_tensors_to_tensordict(metadata: BatchMeta, values: list[Tensor]) -> TensorDict:
        """
        Reconstruct a TensorDict from a list of values using metadata.
        The values list is assumed to be in the same order as keys generated by `_generate_keys`.
        According to field names and global indexes in metadata, this method can determine
        which dict key and which row this tensor belongs to. Then it reshapes the flat tensors list
        back into a structured TensorDict .

        Args:
            metadata (BatchMeta): Metadata containing global indexes and field names.
            values (list[Tensor]): List of tensors in field-major order.
        Returns:
            TensorDict: Reconstructed tensor dictionary with batch size equal to number of samples.
        """
        global_indexes = metadata.global_indexes
        field_names = sorted(metadata.field_names)
        expected_length = len(global_indexes) * len(field_names)
        if len(values) != expected_length:
            raise ValueError(f"Length of values ({len(values)}) does not match expected ({expected_length})")

        if len(values) == 0:
            return TensorDict({}, batch_size=len(global_indexes))

        grouped_data: dict[str, list[Tensor]] = {field: [] for field in field_names}

        # Group values by field_name
        # TODO: Performance optimize
        value_idx = 0
        for field in field_names:
            for _ in range(len(global_indexes)):
                grouped_data[field].append(values[value_idx])
                value_idx += 1

        # Stack or nest tensors per field
        # TODO: These codes about data merging will serve as a general function
        merged_data = {}
        for field, data_list in grouped_data.items():
            if all(isinstance(item, torch.Tensor) for item in data_list):
                try:
                    merged_data[field] = torch.stack(data_list)
                except RuntimeError:
                    try:
                        # Fallback to nested tensor if shapes are irregular
                        merged_data[field] = torch.nested.as_nested_tensor(data_list)
                    except Exception:
                        merged_data[field] = NonTensorStack(*data_list)
            else:
                merged_data[field] = NonTensorStack(*data_list)

        return TensorDict(merged_data, batch_size=len(global_indexes))

    @staticmethod
    def _get_shape_type_list(metadata: BatchMeta):
        """
        Extract the expected shape and dtype for each field-sample pair in metadata.
        The order matches the key/value order: sorted by field name, then by global index.

        Args:
            metadata (BatchMeta): Metadata containing sample and field information.
        Returns:
            tuple[list[torch.Size], list[torch.dtype]]: Two lists containing the shape and dtype
            for each tensor to be retrieved.
        """
        shapes = []
        dtypes = []
        for field_name in sorted(metadata.field_names):
            for index in range(len(metadata)):
                field = metadata.samples[index].get_field_by_name(field_name)
                shapes.append(field.shape)
                dtypes.append(field.dtype)
        return shapes, dtypes

    async def put_data(self, data: TensorDict, metadata: BatchMeta) -> None:
        """
        Store tensor data in the backend storage and notify the controller.

        Serializes the input tensors, stores them using the storage client,
        extracts per-sample dtype and shape information, and sends a notification
        to the controller that new data is available.
        """
        if not metadata.field_names:
            logger.warning("Attempted to put data, but metadata contains no fields.")
            return
        keys = self._generate_keys(data.keys(), metadata.global_indexes)
        values = self._generate_values(data)
        self.storage_client.put(keys=keys, values=values)

        per_field_dtypes = {}
        per_field_shapes = {}

        # Initialize the data structure for each global index
        for global_idx in metadata.global_indexes:
            per_field_dtypes[global_idx] = {}
            per_field_shapes[global_idx] = {}

        # For each field, extract dtype and shape for each sample
        for field_name, field_data in data.items():
            for i, data_item in enumerate(field_data):
                global_idx = metadata.global_indexes[i]
                per_field_dtypes[global_idx][field_name] = (
                    getattr(data_item, "dtype", None) if isinstance(data_item, Tensor) else None
                )
                per_field_shapes[global_idx][field_name] = (
                    getattr(data_item, "shape", None) if isinstance(data_item, Tensor) else None
                )

        # Get current data partition id
        # Note: Currently we only support putting to & getting data from a single data partition simultaneously,
        # but in the future we may support putting to & getting data from multiple data partitions concurrently.
        partition_id = metadata.samples[0].partition_id
        # notify controller that new data is ready
        await self.notify_data_update(
            partition_id, list(data.keys()), metadata.global_indexes, per_field_dtypes, per_field_shapes
        )

    async def get_data(self, metadata: BatchMeta) -> TensorDict:
        """
        Retrieve tensor data from the backend storage.

        Fetches tensors using the provided metadata, reconstructs them with the
        correct shapes and dtypes, and merge them as a TensorDict according to metadata.
        """
        if not metadata.field_names:
            logger.warning("Attempted to get data, but metadata contains no fields.")
            return TensorDict({}, batch_size=len(metadata))
        keys = self._generate_keys(metadata.field_names, metadata.global_indexes)
        shapes, dtypes = self._get_shape_type_list(metadata)
        values = self.storage_client.get(keys=keys, shapes=shapes, dtypes=dtypes)
        return self._merge_tensors_to_tensordict(metadata, values)

    async def clear_data(self, metadata: BatchMeta) -> None:
        """Remove stored data associated with the given metadata."""
        if not metadata.field_names:
            logger.warning("Attempted to clear data, but metadata contains no fields.")
            return
        keys = self._generate_keys(metadata)
        self.storage_client.clear(keys=keys)
